name:          Code Guide by @mdo
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://mdo.github.com/code-guide

markdown:      rdiscount
permalink:     pretty
pygments:      true
